version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smartfootball-mysql
    environment:
      MYSQL_ROOT_PASSWORD: SmartFootball2024!
      MYSQL_DATABASE: smart_football
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - smartfootball-network

  java-service:
    build:
      context: ./backend/java-service-api
      dockerfile: Dockerfile
    container_name: smartfootball-java
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart_football
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SmartFootball2024!
    ports:
      - "8080:8080"
    networks:
      - smartfootball-network

  python-ai:
    build:
      context: ./backend/py-ai-api
      dockerfile: Dockerfile
    container_name: smartfootball-python
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_PATH=/app/models
    ports:
      - "8000:8000"
    volumes:
      - ai_models:/app/models
    networks:
      - smartfootball-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartfootball-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
      - REACT_APP_AI_API_URL=http://localhost:8000/api/v1
    depends_on:
      - java-service
      - python-ai
    networks:
      - smartfootball-network

volumes:
  mysql_data:
  ai_models:

networks:
  smartfootball-network:
    driver: bridge 